language: python
sudo: false
cache:
  - pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - DJANGO="<1.6,>=1.5"
    - DJANGO="<1.7,>=1.6"
    - DJANGO="<1.8,>=1.7"
    - DJANGO="<1.9,>=1.8"

matrix:
  allow_failures:
    - env: DJANGO="<1.6,>=1.5"
    - env: DJANGO="<1.7,>=1.6"
install:
  - pip install --upgrade pip
  - pip install .
  - pip install Django$DJANGO
  - pip install -U pytest pytest-django selenium
  - pip install -U flake8 pep8-naming isort pep257
  - pip install -U coveralls
  - sh -e /etc/init.d/xvfb start
script:
  - isort --check-only --recursive --diff .
  - flake8 --jobs=2 .
  - pep257 s3file
  - coverage run --source=s3file runtests.py
after_success:
  - coveralls
