language: python
sudo: false
cache:
  - pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - DJANGO="Django<1.9,>=1.8"
    - DJANGO="Django<1.10,>=1.9"
    - DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
install:
  - pip install --upgrade pip
  - pip install .
  - pip install $DJANGO
  - pip install -U pytest pytest-django selenium
  - pip install -U flake8 pep8-naming isort pep257
  - pip install -U coveralls
  - sh -e /etc/init.d/xvfb start
script:
  - isort --check-only --recursive --diff .
  - flake8 --jobs=2 .
  - pep257 s3file
  - coverage run --source=s3file -m 'pytest'
after_success:
  - coveralls
